export interface Book {
  id: string;
  title: string;
  author: string;
  price: number;
  originalPrice?: number;
  cover: string;
  genre: string;
  rating: number;
  reviews: number;
  description: string;
  pages: number;
  publisher: string;
  publishedDate: string;
  isbn: string;
  inStock: boolean;
  featured?: boolean;
  bestseller?: boolean;
}

export const genres = [
  "All",
  "Fiction",
  "Non-Fiction",
  "Mystery",
  "Romance",
  "Science Fiction",
  "Fantasy",
  "Biography",
  "Self-Help",
  "History",
  "Children's",
];

export const books: Book[] = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 16.99,
    originalPrice: 24.99,
    cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
    genre: "Fiction",
    rating: 4.8,
    reviews: 2847,
    description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
    pages: 304,
    publisher: "Viking",
    publishedDate: "2020-08-13",
    isbn: "978-0525559474",
    inStock: true,
    featured: true,
    bestseller: true,
  },
  {
    id: "2",
    title: "Atomic Habits",
    author: "James Clear",
    price: 18.99,
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop",
    genre: "Self-Help",
    rating: 4.9,
    reviews: 5632,
    description: "No matter your goals, Atomic Habits offers a proven framework for improving every day. Learn how tiny changes can lead to remarkable results.",
    pages: 320,
    publisher: "Avery",
    publishedDate: "2018-10-16",
    isbn: "978-0735211292",
    inStock: true,
    featured: true,
    bestseller: true,
  },
  {
    id: "3",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: 14.99,
    originalPrice: 19.99,
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop",
    genre: "Mystery",
    rating: 4.6,
    reviews: 3421,
    description: "A woman shoots her husband five times and then never speaks another word. A criminal psychotherapist is determined to unravel the mystery.",
    pages: 336,
    publisher: "Celadon Books",
    publishedDate: "2019-02-05",
    isbn: "978-1250301697",
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    title: "Dune",
    author: "Frank Herbert",
    price: 19.99,
    cover: "https://images.unsplash.com/photo-1531072901881-d644216d4bf9?w=400&h=600&fit=crop",
    genre: "Science Fiction",
    rating: 4.7,
    reviews: 8923,
    description: "Set on the desert planet Arrakis, Dune is the story of Paul Atreides, who would become the mysterious man known as Muad'Dib.",
    pages: 688,
    publisher: "Ace",
    publishedDate: "1965-08-01",
    isbn: "978-0441172719",
    inStock: true,
    bestseller: true,
  },
  {
    id: "5",
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 12.99,
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
    genre: "Fiction",
    rating: 4.5,
    reviews: 12453,
    description: "A magical story about following your dreams. An Andalusian shepherd boy travels from Spain to Egypt in search of a treasure buried near the Pyramids.",
    pages: 208,
    publisher: "HarperOne",
    publishedDate: "1988-01-01",
    isbn: "978-0062315007",
    inStock: true,
    featured: true,
  },
  {
    id: "6",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: 15.99,
    originalPrice: 22.00,
    cover: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    genre: "Fiction",
    rating: 4.7,
    reviews: 6789,
    description: "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove. When the handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark.",
    pages: 384,
    publisher: "G.P. Putnam's Sons",
    publishedDate: "2018-08-14",
    isbn: "978-0735219090",
    inStock: true,
    bestseller: true,
  },
  {
    id: "7",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 9.99,
    cover: "https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=400&h=600&fit=crop",
    genre: "Fiction",
    rating: 4.4,
    reviews: 15678,
    description: "The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan. A tale of the American Dream in the Jazz Age.",
    pages: 180,
    publisher: "Scribner",
    publishedDate: "1925-04-10",
    isbn: "978-0743273565",
    inStock: true,
  },
  {
    id: "8",
    title: "Becoming",
    author: "Michelle Obama",
    price: 22.99,
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    genre: "Biography",
    rating: 4.8,
    reviews: 9876,
    description: "An intimate, powerful, and inspiring memoir by the former First Lady of the United States, chronicling her journey from the South Side of Chicago to the White House.",
    pages: 448,
    publisher: "Crown",
    publishedDate: "2018-11-13",
    isbn: "978-1524763138",
    inStock: true,
    bestseller: true,
  },
  {
    id: "9",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 14.99,
    cover: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=400&h=600&fit=crop",
    genre: "Fantasy",
    rating: 4.8,
    reviews: 23456,
    description: "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life. His contentment is disturbed when Gandalf and a company of dwarves arrive on his doorstep.",
    pages: 366,
    publisher: "Mariner Books",
    publishedDate: "1937-09-21",
    isbn: "978-0547928227",
    inStock: true,
    featured: true,
  },
  {
    id: "10",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 8.99,
    cover: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop",
    genre: "Romance",
    rating: 4.6,
    reviews: 18234,
    description: "The story follows the turbulent relationship between Elizabeth Bennet and Fitzwilliam Darcy, showing how pride and prejudice stand in the way of love.",
    pages: 432,
    publisher: "Penguin Classics",
    publishedDate: "1813-01-28",
    isbn: "978-0141439518",
    inStock: true,
  },
  {
    id: "11",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 21.99,
    originalPrice: 28.00,
    cover: "https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&h=600&fit=crop",
    genre: "History",
    rating: 4.7,
    reviews: 7654,
    description: "A groundbreaking narrative of humanity's creation and evolution that explores how biology and history have defined us and enhanced our understanding of what it means to be 'human.'",
    pages: 464,
    publisher: "Harper",
    publishedDate: "2015-02-10",
    isbn: "978-0062316097",
    inStock: true,
    bestseller: true,
  },
  {
    id: "12",
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    price: 7.99,
    cover: "https://images.unsplash.com/photo-1629992101753-56d196c8adf3?w=400&h=600&fit=crop",
    genre: "Children's",
    rating: 4.9,
    reviews: 34567,
    description: "A beloved children's classic that follows a caterpillar as it eats through a variety of foods before transforming into a beautiful butterfly.",
    pages: 26,
    publisher: "World of Eric Carle",
    publishedDate: "1969-06-03",
    isbn: "978-0399226908",
    inStock: true,
    featured: true,
  },
];

export const getFeaturedBooks = () => books.filter((book) => book.featured);
export const getBestsellers = () => books.filter((book) => book.bestseller);
export const getBooksByGenre = (genre: string) =>
  genre === "All" ? books : books.filter((book) => book.genre === genre);
export const getBookById = (id: string) => books.find((book) => book.id === id);
export const searchBooks = (query: string) =>
  books.filter(
    (book) =>
      book.title.toLowerCase().includes(query.toLowerCase()) ||
      book.author.toLowerCase().includes(query.toLowerCase())
  );
